// Created by Namish Kumar in 2022
import { Brand } from "./BrandName.js";
import { RoundedButton } from "./src/ButtonStyle/RoundedButton.js";
import { White } from "./src/Colors/White.js";
import { WidgetStyler } from "./src/Component/WidgetStyler.js";
import { Heading } from "./src/Heading.js";
import { Image } from "./src/Image.js";
import { India } from "./src/India.js";
import { Text } from "./src/Text.js";
const MainBox = new India.Widget.Box(India.Body.get());
const HeadTarget = MainBox.create();
const BoxStyler = new India.Component.WidgetStyler(HeadTarget);
BoxStyler.setBackgroundColor(India.Colors.Black);
BoxStyler.setMargin(0, "px");
BoxStyler.setPadding(15, "px");
const MainHead = new India.Widget.Heading(HeadTarget);
MainHead.text = Brand.getName;
const MainHeadWid = MainHead.create();
const MainHeadStyler = new India.Component.WidgetStyler(MainHeadWid);
MainHeadStyler.setTextColor(India.Colors.White);
const MainText = new Text(HeadTarget);
MainText.text = "The JS FrameWork built for modern developers. Learn once and write anywhere.";
const BaseText = MainText.create();
const myTextStyler = new WidgetStyler(BaseText);
myTextStyler.setTextColor(White);
const myBodyStyler = new WidgetStyler(India.Body.get());
myBodyStyler.setMargin(0, "px");
const mainButton = new RoundedButton(HeadTarget);
mainButton.text = "Learn IndiaJS";
const MainButton = mainButton.create();
MainButton.style.fontWeight = "bold";
const Query1 = new Heading(India.Body.get());
Query1.text = "What is IndiaJS?";
const baseq1 = Query1.create();
const baseStyler = new WidgetStyler(baseq1);
baseStyler.setMargin(8, "px");
const Body = India.Body.get();
const newText = new Text(Body);
newText.text = "It is the JS FrameWork built for modern developers. Learn once and write anywhere.";
const InformText = newText.create();
new WidgetStyler(InformText).setMargin(8, "px");
const BrandImage = new Image(India.Body.get());
BrandImage.imageSrc = "./Brand.png";